### ISSUE TITLE
% of each type of colorblindness would be useful in the menu

### ISSUE THREAD

**Issue by ivanassen** [oftheheadland/Colorblindly#16]
Maybe add next to each of the types of colorblindness an estimate of its frequency of occurance in the general population - for example, monochromacy is extremely rare, and it's relatively more important for designers to focus on the more common types.

One source of percentages I found online is this:
http://www.colourblindawareness.org/colour-blindness/types-of-colour-blindness/

**Comment by oftheheadland** [comment]
I think this is a great idea, part of the goal of Colorblindly is to educate. I believe this table has the exact rates.
 
![image](https://user-images.githubusercontent.com/17204883/47188104-a5376100-d304-11e8-9b32-9bd48b155497.png)

Any thoughts on if the female statistics should be included? Might appear sexist to only list the male stats, but colorblind women are incredibly rare and the UI would become cluttered with both genders. Open to ideas 😃

**Comment by ivanassen** [comment]
Maybe add just a line with a smaller font at the bottom saying something like

(numbers for men only; colorblindnes among women is extremely rare)

**Comment by oftheheadland** [comment]
Added statistics to the readme.md
