### ISSUE TITLE
CSS issue with Colorblindly

### ISSUE THREAD

**Issue by yonsaber** [oftheheadland/Colorblindly#19]
I noted today on a page with a fixed header, if I enabled Colorblindly, then the fixed header would vanish!

I grabbed a random page with a known fixed header (Google searched it) and making sure the actual header stayed in place.

Browser / OS: Chrome 70.0.3538.67 on Ubuntu Linux
ColorBlindly Version: 1.1

Reproduction steps:

1. Go to http://www.fixedheadertable.com/ and note the fixed header when scrolled down the page (ensure you scroll down otherwise this won't take place)
2. Enable any of the filters (for my images below, I used Monochromacy)
3. Note that the header is now missing where it was previously fixed to the top of the screen.

Expected behaviour:

- Header to stay in place!

Before enabling
![initialpage](https://user-images.githubusercontent.com/2470450/47354164-f7d29d80-d6b5-11e8-864a-e2886e73a7e2.png)

After enabling
![after](https://user-images.githubusercontent.com/2470450/47354169-f99c6100-d6b5-11e8-9e3e-8d6f58e40332.png)

**Comment by AnandChowdhary** [comment]
This is a Chrome bug which breaks `position: fixed` elements after a CSS filter is applied to `<body>`: https://stackoverflow.com/a/51589509/1656944. Changing the filter to `<html>` should fix it.
