### ISSUE TITLE
Header on Tildes.net not recolored

### ISSUE THREAD

**Issue by rlucadou** [oftheheadland/Colorblindly#21]
On the website tildes.net, the header is not affected by any mode. The website has multiple theme options (scroll to the bottom of the page to access them if you don't have an account), and I have not seen it work on any of them.

Normal appearance (Solarized Dark theme):
![image](https://user-images.githubusercontent.com/22415965/64082304-e8ab7b80-ccda-11e9-8177-671d41367908.png)
Note how the background of the header element (which encases the rest of the page contents) is not affected:
![image](https://user-images.githubusercontent.com/22415965/64082300-d2052480-ccda-11e9-95c1-49efd0e5c8fc.png)
![image](https://user-images.githubusercontent.com/22415965/64082303-e3e6c780-ccda-11e9-946c-705e7d9c03ac.png)

**Comment by oftheheadland** [comment]
Appears to be working now, thank you. Try reinstalling the extension if you have problems.
https://tildes.net/
