### ISSUE TITLE
Color simulation accuracy?

### ISSUE THREAD

**Issue by chrisweis** [oftheheadland/Colorblindly#27]
When I compare the results of Colorblindly against multiple online vision simulators, it seems like Colorblindly is different.  Other tools show as browns where Colorblindly shows as greys.  Has there been testing of the results to confirm their accuracy?  Tools used for comparison:

https://www.color-blindness.com/coblis-color-blindness-simulator/
https://pilestone.com/pages/color-blindness-simulator-1
Edge Chromium: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/emulate-vision-deficiencies

**Comment by dkreidler** [comment]
Was this question ever addressed? I noticed comparing results against color wheels that the Green-Blind and Red-Blind results were almost identical. 
![image](https://user-images.githubusercontent.com/19493034/119387622-31694c00-bc97-11eb-9238-9ef7ad885625.png)
![image](https://user-images.githubusercontent.com/19493034/119387678-42b25880-bc97-11eb-9350-37382bd896f9.png)
I don't know much about color blindness, but considering the colors being affected are almost the opposite of each other (red should just be one of the three cones, green should be both of the yellow and blue cones), it was surprising to see such similar results. Thanks!

**Comment by oftheheadland** [comment]
@chrisweis @dkreidler Thank you for bringing this to my attention and my apologies for the delayed response.

You both bring up great points. I am not a scientist nor am I an ophthalmologist so I will try to answer to the best of my ability. Take all information below with a grain of salt.

### 1. @chrisweis's question: Colorblindly differs from other colorblindness simulators
This is true, and other colorblindness simulators can differ from each other. These differences result from the methods and color matrices they use. You will find other simulators differ from each other as well. My color matrices are sourced from various public online research sources, the goal of which were to approximate values for simulating colorblindness. The color altering process that Colorblindly uses is by no means perfect but it is a close approximation. The results of these papers and values varies and are all available online if you are curious in researching colorblindness simulation further.  

---

### 2. @dkreidler's question: Green-Blind (Deuteranopia) and Red-blind (Protanopia) look identical, how could this be possible?
I'm afraid this one is out my league for explaining the actual mechanics behind the cause. I can however direct you to other resources where you will find this same similarity like these YouTube videos comparing the two:

https://www.youtube.com/watch?v=6RuOt28orRI
https://www.youtube.com/watch?v=wZLABgekBfI

There is a slight difference between the two videos above, but not much. I won't make a fool of myself attempting to explain rods and cones and light in a GitHub issue, it's outside my realm. You will find this phenomenon across any colorblindness simulator out there. It is quite peculiar.

---

An important idea to keep in mind about Colorblindly and other simulators is that they are just that - simulators. This isn't truly how colorblind people see. Monochromacy (Achromatopsia) is a simple one and likely pretty accurate - they can't see anything but shades of gray. Other vision impairments, like the ones that end in -anomaly, are much less black and white (no pun intended). Red-Weak (Protanomaly) is not the absence of red vision, it means the individual has trouble seeing the color red. The amount of red they are able to see is a spectrum that will vary across different people with the condition. Protanopia is complete red-blindness. This simulator and others are a best guess at how colorblind people see the world.

I hope this information helps and I encourage everyone reading this to research further about colorblindness.
