### ISSUE TITLE
Reopening: the extension is currently broken and nonfunctional.

### ISSUE THREAD

**Issue by MechaM42** [oftheheadland/Colorblindly#31]
After recent Chrome security model updates, this extension no longer works. The extension can only run "when you click on the extension" and fails to apply the color settings to viewed websites. Right-clicking to allow for a specific site, or "on all sites," is no longer available in Chrome.

Developer's condescending response was "You just have to click the extension friend. Complain to Google" but **clicking the extension does not work**, and **selecting modes of colorblindness results in no change to the displayed webpage.**

Chrome version on which issue is readily duplicated on multiple computers: 120.0.6099.225 (Official Build) (64-bit)

Chrome devtools error:
"popup.html:1 Uncaught (in promise) Error: Cannot access contents of the page. Extension manifest must request permission to access the respective host."

**Comment by oftheheadland** [comment]
Thank you for raising the issue, I have submitted the extension to the Chrome Web Store with updated permissions!
