### ISSUE TITLE
Selected filter not being maintained

### ISSUE THREAD

**Issue by yonsaber** [oftheheadland/Colorblindly#9]
This is a really useful tool, thank you for all the work you've put into it!

When testing in Chrome I noticed if I selected a filter, then clicked about on a page, then went back to the pop-up to select a filter, it would show the first item being selected instead of the active filter.

Browser / OS: Chrome 69.0.3497.100 on Ubuntu Linux

Reproduction steps:
* Open filter pop-up window
* Select any filter
* Close pop-up
* Open pop-up, first item is selected, even though the filter is applied still

Expected:
If I select "Blue-Blind / Tritanopia", close the pop-up then re-open it, then that should still be the selected filter

**Comment by yonsaber** [comment]
@ItamarShDev nice fix! Just seen this update come through on the app store and seems to be working nicely :D Thank you
@oftheheadland Thank you for accepting the PR so fast!

**Comment by ItamarShDev** [comment]
@yonsaber thank you! gave me the opportunity to expand my horizons.
@oftheheadland Wow it was fast! thank you very much for accepting the PR so fast.
happy hacktoberfest!
